### ISSUE TITLE
footer.css

### ISSUE THREAD

**Issue by GucciGui** [UnderTheCraft/TheDistillery#12]

**Comment by SveaMahlke** [comment]
Problem with sticking the footer at the bottom;

**Comment by SveaMahlke** [comment]
> Problem with sticking the footer at the bottom;

solution: Issue #23

**Comment by UnderTheCraft** [comment]
Anpassen der Farbe vom Impressum?

**Comment by UnderTheCraft** [comment]
Beim Zusammenschieben der Seite wird der Footer schlecht erkennbar. -> Vlt. anderes anordnen der Informationen (mit Media Queries)

**Comment by UnderTheCraft** [comment]
Die File heißt noch "Footer.css", sollte man noch klein schreiben 🙈

**Comment by UnderTheCraft** [comment]
> Anpassen der Farbe vom Impressum?

Finde es seltsam, dass manchmal das Impressum im Footer jetzt das neue grau hat, aber zum Teil ist es noch das alte blau... Dieses WebProg verwirrt mich 😄
