### ISSUE TITLE
header.html

### ISSUE THREAD

**Issue by GucciGui** [UnderTheCraft/TheDistillery#13]
Header File

**Comment by UnderTheCraft** [comment]
Fände eine andere Farbe des Suchbuttons ganz nice 🙈  Vllt Schwarz oder so? 😄 
Und man könnte statt "Suche" in das Feld noch was nettes schreiben (also der placeholder), wie "Nach was suchst du?" 😋

**Comment by UnderTheCraft** [comment]
Die navbar müsste ab 780px breite eingeklappt werden, da hier die einzelnen Buttons anfang sich zu verschieben
Die einzelnen Buttons müssten dann in einem Dropdown Menü erscheinen, in was zur Zeit noch nicht angezeigt wird.
Die Suchleiste müsste da dann auch reingepackt werden, da diese ab 575px Probleme bereitet.

**Comment by UnderTheCraft** [comment]
In der Navbar wird das item mit der Klasse "active" fettgedruckt angezeigt, was anzeigt auf welcher Seite sich der User gerade befindet. Nur wird leider dieser active Status nicht geändert, sodass immer der Katalog fett gedruckt ist.
